{% set name = "dataconf" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataconf-{{ version }}.tar.gz
  sha256: 0c107e1d6fc4ca4c133ee7c8540417a737bac7d45bbca22b9bc876e212518d81

build:
  number: 0
  noarch: python
  entry_points:
    - dataconf = dataconf.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.8
  run:
    - pyhocon >=0.3.54,<0.4.0
    - python >=3.8
    - python-dateutil >=2.8.1,<3.0.0

test:
  imports:
    - dataconf
  commands:
    - pip check
    - dataconf --help
  requires:
    - pip

about:
  home: https://github.com/zifeo/dataconf
  summary: Simple dataclasses configuration management for Python with hocon/json/yaml/properties/env-vars/dict support.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
