{% set name = "dataconf" %}
{% set version = "3.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dataconf-{{ version }}.tar.gz
  sha256: 5150ddba8689e34eb6245a89f022bcca115c9f3c5d20f789f87c6c4ebe688446

build:
  number: 0
  noarch: python
  entry_points:
    - dataconf = dataconf.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.1.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - pyhocon <0.4.0,>=0.3.61
    - isodate >=0.6.1,<0.7.0
    - python-dateutil >=2.9.0,<3.0.0
    - pyyaml >=6.0.2,<7.0.0
    - pyparsing >=3.1.4,<4.0.0

test:
  imports:
    - dataconf
  commands:
    # Disabling pip check because upstream pinned to python-dateutil 2.9.0.post0, can restore when we move off of that
    # - pip check
    - dataconf --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zifeo/dataconf
  summary: Simple dataclasses configuration management for Python with hocon/json/yaml/properties/env-vars/dict support
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dwsmith1983
    - thewchan
    - zifeo
