{% set name = "dataconf" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataconf-{{ version }}.tar.gz
  sha256: 041325ed42f36637786a9712688359410184c62738945f7a7555cf360e6f0103

build:
  number: 0
  noarch: python
  entry_points:
    - dataconf = dataconf.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.1.0
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - pyhocon >=0.3.60,<0.4.0
    - isodate >=0.6.1,<0.7.0
    - python-dateutil >=2.8.2,<3.0.0
    - pyyaml >=6.0.1,<7.0.0
    - pyparsing >=3.1.2,<4.0.0

test:
  imports:
    - dataconf
  commands:
    - pip check
    - dataconf --help
  requires:
    - pip

about:
  home: https://github.com/zifeo/dataconf
  summary: Simple dataclasses configuration management for Python with hocon/json/yaml/properties/env-vars/dict support
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dwsmith1983
    - thewchan
    - zifeo
